name: Go deployment

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install gcc-aarch64-linux-gnu
      run: sudo apt install -y gcc-aarch64-linux-gnu libc6-dev-arm64-cross

    - name: Go Build arm64
      run: GOARCH=arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc go build -o ./mr-weasel

    - name: Go Test -v
      run: go test -v ./...

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          mr-weasel
          migrations
          .service

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    environment: dev
    steps:
      - name: Download app artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: copy file to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: build/
          target: ~/app/mr-weasel
          strip_components: 1

      - name: Migrage database and Restart service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ~/app/mr-weasel
            source .env
            sudo systemctl stop mr-weasel.service
            ~/go/bin/goose -dir=./migrations ${GOOSE_DRIVER} ${GOOSE_DBSTRING} up
            sudo systemctl start mr-weasel.service
          # dev ALL = NOPASSWD: /bin/systemctl stop mr-weasel.service
          # dev ALL = NOPASSWD: /bin/systemctl start mr-weasel.service
