name: Go Build, Test, Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install gcc-aarch64-linux-gnu
      run: sudo apt install -y gcc-aarch64-linux-gnu libc6-dev-arm64-cross

    - name: Build arm64
      run: GOARCH=arm64 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc go build -o ./bin/main-linux-arm64

    - name: Test
      run: go test -v ./...

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: bin

    - name: Upload migrations artifacts
      uses: actions/upload-artifact@v3
      with:
        name: migrations
        path: migrations

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: app
  
      - name: Download migrations artifacts
        uses: actions/download-artifact@v3
        with:
          name: migrations
          path: app/migrations

      - name: Copy artifacts via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY}}
          source: app
          target: ~/app
